import { Nunito_Sans } from "next/font/google";

import Header from "@/components/header/header";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  weight: ["300", "600", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "REST countries API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={nunitoSans.className}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
